[package]
name = "bin"
version = "0.1.0"
edition = "2024"

[dependencies]
api = { path = "../api" }
domain = { path = "../domain" }
core = { path = "../core" }
infra = { path = "../infra" }

anyhow.workspace = true
tokio.workspace = true
dotenv.workspace = true
clap.workspace = true